site_name: GitBridge Documentation
site_description: GitHub Repository Synchronization Tool - Documentation
site_author: Nevedomski Sergei
site_url: https://nevedomski.github.io/gitbridge/   # ← ensure lowercase repo name
repo_url: https://github.com/nevedomski/gitbridge
repo_name: gitbridge
edit_uri: edit/main/docs/
copyright: Copyright © 2025 Nevedomski Sergei

theme:
  name: material
  language: en

  # custom_dir: docs/overrides

  font:
    text: Inter       # ← crisper body font
    code: Roboto Mono

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey   # ← calmer, “engineering” feel
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    # Navigation (trim to the most useful; less clutter)
    - navigation.instant
    # - navigation.instant.prefetch      # ← disable: can cause flicker/waste
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes                 # ← keep section index pages
    - navigation.top
    - navigation.footer
    # - navigation.sections              # ← disable: reduces sidebar noise
    # Table of Contents
    - toc.follow
    - toc.integrate
    # Search
    - search.suggest
    - search.highlight
    - search.share
    # Header
    - header.autohide
    # Content
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view
    # Announce
    - announce.dismiss

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - search:
      separator: '[\s\-\.]'
      lang:
        - en
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [gitbridge]  # update if your package lives under src/
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: google
            merge_init_into_class: true
            separate_signature: true
            show_if_no_docstring: false
            members_order: source
            show_submodules: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
      enable_git_follow: false
strict: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
      title: On this page
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      use_pygments: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: nevedomski
      repo: gitbridge
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      check_paths: true

extra:
  social:
    - icon: material/file-arrow-left-right-outline
      link: https://github.com/nevedomski/gitbridge
      name: Changelog
    - icon: material/license
      link: https://pypi.org/project/gitbridge/
      name: License
    - icon: material/github
      link: https://github.com/nevedomski/gitbridge
      name: GitBridge on GitHub
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/gitbridge/
      name: GitBridge on PyPI
  logo:
    icon: images/logo-light.svg
    icon_dark: images/logo-dark.svg
  favicon: images/favicon.ico
  banner:
    light: images/banner-light.svg
    dark: images/banner-dark.svg
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  consent:
    title: Cookie consent
    description: |
      We use cookies to recognize your repeated visits and preferences, and to
      measure the effectiveness of our documentation.
    actions: [accept, reject, manage]
  generator: false
  
extra_css:
  - stylesheets/extra.css?v=3

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Consider moving Changelog/License to footer links; keeps sidebar focused on docs.
nav:
  - Home:
    - index.md
    - changelog.md
    - license.md
  
  - Getting Started:
    - getting-started/index.md
    - getting-started/installation.md
    - getting-started/quick-start.md
    - getting-started/first-sync.md
    - getting-started/configuration-basics.md
  
  - User Guide:
    - user-guide/index.md
    - user-guide/sync-methods.md
    - user-guide/configuration.md
    - user-guide/authentication.md
    - user-guide/incremental-sync.md
    - user-guide/branch-management.md
    - user-guide/corporate-setup.md
    - user-guide/proxy-configuration.md
    - user-guide/ssl-certificates.md
  
  - CLI Reference:
    - cli/index.md
    - cli/sync-command.md
    - cli/status-command.md
  
  - Architecture:
    - architecture/index.md
  
  - API Reference:
    - api/index.md
  
  - Troubleshooting:
    - troubleshooting/index.md
    - troubleshooting/common-issues.md
    - troubleshooting/network-errors.md
    - troubleshooting/authentication-errors.md
    - troubleshooting/proxy-issues.md
    - troubleshooting/ssl-errors.md
    - troubleshooting/browser-automation.md


