site_name: GitBridge Documentation
site_description: GitHub Repository Synchronization Tool - Documentation
site_author: GitBridge Team
site_url: https://nevedomski.github.io/gitBridge/
repo_url: https://github.com/nevedomski/gitbridge
repo_name: gitbridge
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2025 GitBridge Team

theme:
  name: material
  language: en
  
  font:
    text: Roboto
    code: Roboto Mono
  
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    # Navigation
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    # Table of Contents
    - toc.follow
    - toc.integrate
    # Search
    - search.suggest
    - search.highlight
    - search.share
    # Header
    - header.autohide
    # Content
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view
    # Announce
    - announce.dismiss
  
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - search:
      separator: '[\s\-\.]'
      lang:
        - en
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [gitbridge]
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: google
            merge_init_into_class: true
            separate_signature: true
            show_if_no_docstring: false
            members_order: source
            show_submodules: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
      title: On this page
  - tables
  
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: nevedomski
      repo: gitbridge
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      check_paths: true

extra:
  version:
    provider: mike
    default: stable
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nevedomski/gitbridge
      name: GitBridge on GitHub
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/gitbridge/
      name: GitBridge on PyPI
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/nevedomski/gitbridge/issues/new/?title=[Feedback]+{title}">feedback form</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage
  generator: false
  status:
    new: Recently added
    deprecated: Deprecated

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
    - index.md
    - changelog.md
    - license.md
  
  - Getting Started:
    - getting-started/index.md
    - getting-started/installation.md
    - getting-started/quick-start.md
    - getting-started/first-sync.md
  
  - User Guide:
    - user-guide/index.md
    - user-guide/sync-methods.md
    - user-guide/configuration.md
    - user-guide/authentication.md
    - user-guide/incremental-sync.md
    - user-guide/branch-management.md
    - user-guide/corporate-setup.md
    - user-guide/proxy-configuration.md
  
  - CLI Reference:
    - cli/index.md
    - cli/sync-command.md
  
  - Architecture:
    - architecture/overview.md
  
  - API Reference:
    - api/index.md
  
  - Troubleshooting:
    - troubleshooting/index.md
    - troubleshooting/common-issues.md