name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      target:
        description: 'Publish target'
        required: true
        default: 'testpypi'
        type: choice
        options:
          - testpypi
          - pypi

jobs:
  build-and-publish:
    name: 📦 Build and Publish
    runs-on: ubuntu-latest
    environment:
      # Use pypi environment for releases, or the selected target for manual runs
      name: ${{ github.event_name == 'release' && 'pypi' || github.event.inputs.target }}
      url: ${{ github.event_name == 'release' && 'https://pypi.org/p/gitbridge' || (github.event.inputs.target == 'testpypi' && 'https://test.pypi.org/p/gitbridge' || 'https://pypi.org/p/gitbridge') }}
    permissions:
      id-token: write  # Required for trusted publishing
      contents: write  # Required for uploading release assets
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for proper versioning
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      
      - name: Build distribution
        run: |
          echo "Building distribution packages..."
          uv build
          
          echo ""
          echo "=== Build artifacts ==="
          ls -la dist/
          
          echo ""
          echo "=== Package metadata ==="
          pip install pkginfo
          python -c "from pkginfo import Wheel; import glob; w = Wheel(glob.glob('dist/*.whl')[0]); print(f'Package: {w.name}\\nVersion: {w.version}\\nPython: {w.requires_python}')"
      
      - name: Publish to TestPyPI
        if: github.event.inputs.target == 'testpypi'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          print-hash: true
          skip-existing: true  # Don't fail if version already exists
      
      - name: Publish to PyPI
        if: github.event_name == 'release' || github.event.inputs.target == 'pypi'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
      
      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          echo "Uploading distribution packages to GitHub release..."
          gh release upload '${{ github.event.release.tag_name }}' dist/* --clobber
          
          echo ""
          echo "✅ Release assets uploaded successfully"
          echo "View release: ${{ github.event.release.html_url }}"
      
      - name: Show installation instructions
        run: |
          echo ""
          echo "📦 Installation Instructions:"
          echo "=============================="
          if [[ "${{ github.event.inputs.target }}" == "testpypi" ]]; then
            echo "To install from TestPyPI:"
            echo "  pip install -i https://test.pypi.org/simple/ gitbridge"
            echo ""
            echo "With extras:"
            echo "  pip install -i https://test.pypi.org/simple/ gitbridge[browser]"
          else
            echo "To install from PyPI:"
            echo "  pip install gitbridge"
            echo ""
            echo "With extras:"
            echo "  pip install gitbridge[browser]"
            echo ""
            echo "For development:"
            echo "  pip install gitbridge[dev]"
          fi