name: Ruff Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 🛑 Ruff lint check
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --select F,E"